---
name: Tagged Release

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.17

      - name: Build
        run: |
          GOOS=windows GOARCH=386 go build -ldflags "-s -w" -o build/gosfs-windows-x86.exe *.go
          GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" -o build/gosfs-windows.exe *.go
          GOOS=linux GOARCH=386 go build -ldflags "-s -w" -o build/gosfs-linux-x86 *.go
          GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o build/gosfs-linux *.go
          GOOS=darwin GOARCH=amd64 go build -ldflags "-s -w" -o build/gosfs-darwin *.go

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/*
